Homework 1
================
Gauri Bhatkhande

This is my solution to HW1

*Loaded the packages that I need for this project.*

``` r
library(tidyverse)
```

    ## ── Attaching packages ────────────────────────────────────────────────────── tidyverse 1.3.0 ──

    ## ✓ ggplot2 3.3.2     ✓ purrr   0.3.4
    ## ✓ tibble  3.0.3     ✓ dplyr   1.0.2
    ## ✓ tidyr   1.1.2     ✓ stringr 1.4.0
    ## ✓ readr   1.3.1     ✓ forcats 0.5.0

    ## ── Conflicts ───────────────────────────────────────────────────────── tidyverse_conflicts() ──
    ## x dplyr::filter() masks stats::filter()
    ## x dplyr::lag()    masks stats::lag()

``` r
library(palmerpenguins)
```

## Problem 1

*Create a dataframe comprised of the specified elements:*

``` r
prob1_df = 
tibble(
    samp = rnorm(10),
    samp_gt_0 = samp > 0, 
    char_vec = c("a", "b", "c", "d", "e", "f", "g", "h", "i", "j"),
    factor_vec = factor(c("low", "low", "low", "mod", "mod", "mod", "mod", "high", "high", "high" ))
)
```

*Take the mean of each variable in my data frame.*

``` r
mean(pull(prob1_df, samp))
```

    ## [1] -0.3647748

``` r
mean(pull(prob1_df, samp_gt_0))
```

    ## [1] 0.3

``` r
mean(pull(prob1_df, char_vec))
```

    ## Warning in mean.default(pull(prob1_df, char_vec)): argument is not numeric or
    ## logical: returning NA

    ## [1] NA

``` r
mean(pull(prob1_df, factor_vec))
```

    ## Warning in mean.default(pull(prob1_df, factor_vec)): argument is not numeric or
    ## logical: returning NA

    ## [1] NA

I can take the means of numbers and logical but not character or factor.
Logical gets understood by R as 1 or 0 and hence R at the backend does
that calculation for us and gives the mean

``` r
as.numeric(pull(prob1_df, samp_gt_0))
as.numeric(pull(prob1_df, char_vec))
```

    ## Warning: NAs introduced by coercion

``` r
as.numeric(pull(prob1_df, factor_vec))
```

Can convert the logical and factor vectors to numerics and then take
means but could not convert the character vector to numeric and hence
could not take the mean

``` r
as.numeric(pull(prob1_df, samp_gt_0)) * pull(prob1_df, samp)
```

    ##  [1] 0.0000000 0.0000000 0.4558931 0.5869544 0.0000000 0.0000000 0.0000000
    ##  [8] 0.0000000 1.2564178 0.0000000

``` r
as.factor(pull(prob1_df, samp_gt_0)) * pull(prob1_df, samp)
```

    ## Warning in Ops.factor(as.factor(pull(prob1_df, samp_gt_0)), pull(prob1_df, : '*'
    ## not meaningful for factors

    ##  [1] NA NA NA NA NA NA NA NA NA NA

``` r
as.numeric(as.factor(pull(prob1_df, samp_gt_0))) * pull(prob1_df, samp)
```

    ##  [1] -0.6931106 -0.6831394  0.9117862  1.1739089 -1.9037049 -0.3132661
    ##  [7] -0.5951069 -1.4456048  2.5128356 -0.3130806

## Problem 2

*I loaded the penguins dataset:*

``` r
data("penguins", package = "palmerpenguins")
```

*Description of the dataset:*

``` r
nrow(penguins)
```

    ## [1] 344

``` r
ncol(penguins)
```

    ## [1] 8

There are **344 observations** and **8 variables** in the dataset
*penguins*

*I want to explore which are the 8 variable names:*

``` r
variable.names(penguins)
```

    ## [1] "species"           "island"            "bill_length_mm"   
    ## [4] "bill_depth_mm"     "flipper_length_mm" "body_mass_g"      
    ## [7] "sex"               "year"

The names of the variables in the dataset are *species, island,
bill\_length\_mm, bill\_depth\_mm, flipper\_length\_mm, body\_mass\_g,
sex, year*

*To find the categories of species and islands and the number of
penguins pertaining to each species and island:*

``` r
levels(pull(penguins, species))
```

    ## [1] "Adelie"    "Chinstrap" "Gentoo"

``` r
levels(pull(penguins, island))
```

    ## [1] "Biscoe"    "Dream"     "Torgersen"

``` r
count(penguins, species)
```

    ## # A tibble: 3 x 2
    ##   species       n
    ##   <fct>     <int>
    ## 1 Adelie      152
    ## 2 Chinstrap    68
    ## 3 Gentoo      124

``` r
count(penguins, island)
```

    ## # A tibble: 3 x 2
    ##   island        n
    ##   <fct>     <int>
    ## 1 Biscoe      168
    ## 2 Dream       124
    ## 3 Torgersen    52

``` r
count(penguins, sex)
```

    ## # A tibble: 3 x 2
    ##   sex        n
    ##   <fct>  <int>
    ## 1 female   165
    ## 2 male     168
    ## 3 <NA>      11

The three penguin species are *Adelie (n = 152), Chinstrap (n = 68),
Gentoo (n=124)* The islands are named *Biscoe (n = 168), Dream (n = 124)
and Torgersen (n = 52)* *165* penguins are *females*, *168* are *males*
and *11* are *unknown*.

*To find the mean size measurements:*

``` r
mean (pull(penguins, bill_length_mm),na.rm = TRUE)
```

    ## [1] 43.92193

``` r
mean (pull(penguins, bill_depth_mm),na.rm = TRUE)
```

    ## [1] 17.15117

``` r
mean (pull(penguins, flipper_length_mm),na.rm = TRUE)
```

    ## [1] 200.9152

``` r
mean (pull(penguins, body_mass_g),na.rm = TRUE)
```

    ## [1] 4201.754

The mean *bill length* for the penguins is *43.92 mm.* The mean *bill
depth* for the penguins is *17.15 mm.* The mean *flipper length* for the
penguins is *200.91 mm.* The mean *body mass* for the penguins is
*4201.75 grams.*

I wanted to know the mean size measurements which I believe are
important here and stratified them by the species group. *The mean size
measurements stratified by the species are calculated below:*

``` r
aggregate(penguins[,3:6],list(pull(penguins,species)),mean,na.rm=TRUE)
```

    ##     Group.1 bill_length_mm bill_depth_mm flipper_length_mm body_mass_g
    ## 1    Adelie       38.79139      18.34636          189.9536    3700.662
    ## 2 Chinstrap       48.83382      18.42059          195.8235    3733.088
    ## 3    Gentoo       47.50488      14.98211          217.1870    5076.016

I wanted to know whether the mean sizes for a species differed by the
islands. *Therefore I stratified that relationship with islands.*

``` r
aggregate(penguins[,3:6],list(pull(penguins,island), pull(penguins,species)),mean,na.rm=TRUE)
```

    ##     Group.1   Group.2 bill_length_mm bill_depth_mm flipper_length_mm
    ## 1    Biscoe    Adelie       38.97500      18.37045          188.7955
    ## 2     Dream    Adelie       38.50179      18.25179          189.7321
    ## 3 Torgersen    Adelie       38.95098      18.42941          191.1961
    ## 4     Dream Chinstrap       48.83382      18.42059          195.8235
    ## 5    Biscoe    Gentoo       47.50488      14.98211          217.1870
    ##   body_mass_g
    ## 1    3709.659
    ## 2    3688.393
    ## 3    3706.373
    ## 4    3733.088
    ## 5    5076.016

*I calculated the number of rows and columns in the dataset:*

``` r
nrow(penguins)
```

    ## [1] 344

There are **344 rows** in the *penguins* dataset

``` r
ncol(penguins)
```

    ## [1] 8

There are **8 columns** in the *penguins* dataset

``` r
mean (as.numeric(pull(penguins, flipper_length_mm)),na.rm = TRUE)
```

    ## [1] 200.9152

**The mean flipper length is 200.9152 mm.**

*I made the following scatterplot:*

``` r
y = pull(penguins, flipper_length_mm)
x = pull(penguins, bill_length_mm)
ggplot(penguins, aes(x = x, y = y, color = species)) + geom_point() + labs(x="Bill length", y = "Flipper length") + ggtitle("Scatterplot of flipper length vs bill length of penguins")
```

    ## Warning: Removed 2 rows containing missing values (geom_point).

![](p8105_hw1_gb2685_files/figure-gfm/unnamed-chunk-20-1.png)<!-- -->

*Received the following Warning <message:Removed> 2 rows containing
missing values (geom\_point). This could be because two rows had NA for
flipper length*

``` r
ggsave("scatter_plot1.pdf" )
```

    ## Saving 7 x 5 in image

    ## Warning: Removed 2 rows containing missing values (geom_point).
